version: '3'

services: 
  app:
    image: docker.io/apthailand/suchat_s:icrmchatbot_api_v1.0.0
    build:
        context: .
        dockerfile: ./Dockerfile
    ports: 
      - "5000:5000"
    expose:
      - "5000"
